### ISSUE TITLE
Issue when running

### ISSUE THREAD

**Issue by ghost** [ylimit/androcov#3]
Something like this down below.
I tried changing the sdk version, the same error occurs.
I was running this project on win10, was i missing any dependencies?

D:\androcov-master\target>java -jar androcov-1.0.jar -o D:\androcov-master\output -i C:\Users\tmliu\Desktop\voguegame\1E33A83359CD11ED70A496C78A876196.apk -sdk C:\Users\tmliu\AppData\Local\Android\Sdk\platforms\android-20\android.jar
八月 21, 2017 11:28:14 上午 xyz.ylimit.androcov.Config parseArgs
信息: finish parsing arguments
八月 21, 2017 11:28:14 上午 xyz.ylimit.androcov.Config parseArgs
信息: [inputAPK]C:\Users\tmliu\Desktop\voguegame\1E33A83359CD11ED70A496C78A876196.apk, [outputDir]D:\androcov-master\output
八月 21, 2017 11:28:14 上午 xyz.ylimit.androcov.Main main
信息: OK let's start!
八月 21, 2017 11:28:15 上午 xyz.ylimit.androcov.Instrumenter instrument
信息: Start instrumenting...
Using 'C:\Users\tmliu\AppData\Local\Android\Sdk\platforms\android-20\android.jar' as android.jar
**Exception in thread "main" java.lang.Error: Error loading java.lang.CharSequence**
        at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:128)
        at soot.JastAddJ.Program.getCompilationUnit(Program.java:887)
        at soot.JastAddJ.Program.getLibCompilationUnit_compute(Program.java:1531)
        at soot.JastAddJ.Program.getLibCompilationUnit(Program.java:1514)
        at soot.JastAddJ.Program.lookupLibType_compute(Program.java:1479)
        at soot.JastAddJ.Program.lookupLibType(Program.java:1447)
        at soot.JastAddJ.Program.lookupType_compute(Program.java:1426)
        at soot.JastAddJ.Program.lookupType(Program.java:1407)
        at soot.JastAddJ.Program.Define_TypeDecl_lookupType(Program.java:1995)
        at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
        at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
        at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
        at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
        at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
        at soot.JastAddJ.Expr.lookupType(Expr.java:1186)
        at soot.JastAddJ.TypeAccess.decls_compute(TypeAccess.java:425)
        at soot.JastAddJ.TypeAccess.decls(TypeAccess.java:414)
        at soot.JastAddJ.TypeAccess.refined_TypeScopePropagation_TypeAccess_decl(TypeAccess.java:387)
        at soot.JastAddJ.TypeAccess.decl_compute(TypeAccess.java:460)
        at soot.JastAddJ.TypeAccess.decl(TypeAccess.java:452)
        at soot.JastAddJ.TypeAccess.type_compute(TypeAccess.java:590)
        at soot.JastAddJ.TypeAccess.type(TypeAccess.java:583)
        at soot.JastAddJ.ClassDecl.isCircular_compute(ClassDecl.java:1696)
        at soot.JastAddJ.ClassDecl.isCircular(ClassDecl.java:1673)
        at soot.JastAddJ.ClassDecl.superclass(ClassDecl.java:240)
        at soot.JastAddJ.ClassDecl.supertypeClassDecl(ClassDecl.java:1840)
        at soot.JastAddJ.ClassDecl.subtype_compute(ClassDecl.java:1832)
        at soot.JastAddJ.ClassDecl.subtype(ClassDecl.java:1817)
        at soot.JastAddJ.TypeVariable.supertypeClassDecl(TypeVariable.java:1414)
        at soot.JastAddJ.ClassDecl.subtype_compute(ClassDecl.java:1832)
        at soot.JastAddJ.ClassDecl.subtype(ClassDecl.java:1796)
        at soot.JastAddJ.ClassDecl.instanceOf_compute(ClassDecl.java:1555)
        at soot.JastAddJ.ClassDecl.instanceOf(ClassDecl.java:1548)
        at soot.JastAddJ.ParTypeAccess.typeCheck(ParTypeAccess.java:121)
        at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1284)
        at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
        at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
        at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
        at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
        at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
        at soot.JastAddJ.CompilationUnit.errorCheck(CompilationUnit.java:178)
        at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:58)
        at soot.JavaClassSource.resolve(JavaClassSource.java:54)
        at soot.SootResolver.bringToHierarchy(SootResolver.java:237)
        at soot.SootResolver.bringToSignatures(SootResolver.java:264)
        at soot.SootResolver.processResolveWorklist(SootResolver.java:168)
        at soot.SootResolver.resolveClass(SootResolver.java:129)
        at soot.Scene.loadClass(Scene.java:694)
        at soot.Scene.loadClassAndSupport(Scene.java:679)
        at soot.Scene.loadNecessaryClasses(Scene.java:1353)
        at xyz.ylimit.androcov.Instrumenter.instrument(Instrumenter.java:53)
        at xyz.ylimit.androcov.Main.main(Main.java:15)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4608
        at soot.JastAddJ.BytecodeParser.parseThisClass(BytecodeParser.java:437)
        at soot.JastAddJ.BytecodeParser.parseTypeDecl(BytecodeParser.java:404)
        at soot.JastAddJ.BytecodeParser.parse(BytecodeParser.java:331)
        at soot.JastAddJ.BytecodeParser.read(BytecodeParser.java:27)
        at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:115)
        ... 51 more

Keep me informed, Thank you.

**Comment by ghost** [comment]
converted to Ubuntu, problem solved...
